name: oepd8
recipe: 'drupal8'
config:
  php: '8.0'
  via: 'nginx'
  webroot: './web'
  xdebug: true
  config:
    php: lando.php.ini
services:
  appserver:
    build:
      - composer install
    overrides:
      environment:
        DRUSH_OPTIONS_URI: "https://oepd8.lndo.site"
  pma:
    type: phpmyadmin
