favicon:
  mimetype: image/vnd.microsoft.icon
  path: ''
  url: ''
  use_default: true
features:
  favicon: true
  node_user_picture: true
logo:
  path: ''
  url: ''
  use_default: true
_core:
  default_config_hash: fxOklRTggjGijnUXS8sGVIJl_mrBKX0Sv7iXQfBOXIM
